# Generated by Django 4.1.10 on 2023-08-04 08:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance_tracker', '0002_add_currencies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='currency_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='budget', to='finance_tracker.currency', to_field='code'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='currency_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='expense', to='finance_tracker.currency', to_field='code'),
        ),
        migrations.AlterField(
            model_name='income',
            name='currency_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='income', to='finance_tracker.currency', to_field='code'),
        ),
    ]
