# Generated by Django 4.1.10 on 2023-08-04 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance_tracker', '0003_alter_budget_currency_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='photo',
            field=models.ImageField(blank=True, upload_to='photos_expense'),
        ),
        migrations.AlterField(
            model_name='income',
            name='photo',
            field=models.ImageField(blank=True, upload_to='photos_income'),
        ),
    ]
