# Generated by Django 4.1.10 on 2023-08-04 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance_tracker', '0004_alter_expense_photo_alter_income_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='budget_categories', to='finance_tracker.category'),
        ),
    ]
