# Generated by Django 4.1.10 on 2023-08-04 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance_tracker', '0005_alter_budget_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='due_date',
            field=models.DateField(),
        ),
    ]
